# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7830cba06c859c0bdca28ec29ec278c6e09483e87fdc16349b55ff009b922863d9c9bb028a71e3338e201fead1d2a47e730bd66d23481627a994c4f32e5fdece

test:
  secret_key_base: bce9df048d56291cb696126fd090cc1eea01677b1f73cf2016d58661d3d71926075add186f2f7986e23e35f65fc7cfc704f5afbef9c07d8ecc63624dae21f73b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
